# .goreleaser.yml
# Build customization
project_name: laforge
builds:
  - main: main.go
    binary: laforge
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: -s -w -X main.Name={{.Name}} -X main.Version={{.Version}} -X main.ReleaseDate={{.Date}} -X main.CommitRef={{.Commit}}
# Archive customization
archive:
  format: zip